version: "1"
services:
  web:
    build: .
    cpu_shares: 10
    mem_limit: 256MB
    labels:
      - convox.port.443.protocol=tls
    ports:
      - 80:5000
      - 443:5000
    environment:
      - FLASK_ENV="development"
      - FLASK_DEBUG=true
      - FLASK_TESTING=true
      - FLASK_SECRET_KEY
      - FLASK_DB_URI
    command: ["python", "run.py"]
