version: "2"
services:
  counter:
    build: www
    ports:
      - "80:5000"
      - "443:5000"
    user: nobody
    environment:
      - FLASK_ENV="development"
      - FLASK_DEBUG=true
      - FLASK_TESTING=true
      - FLASK_SECRET_KEY
      - FLASK_DB_URI
    command: ["bin/run"]
    labels:
      - convox.port.443.protocol=tls
